name: space_craft
description: A new Flutter project to create 2D game.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  easy_rich_text: ^1.0.3
  path_provider: ^2.0.1

  change_app_package_name: ^1.0.0
  flutter_riverpod: ^1.0.2
  flutter_lints: ^2.0.1
  equatable: ^2.0.3

  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
    - assets/images/
